services:
  db_server:
    image: postgres
    container_name: 'perpl-test-postgres'
    restart: always
    environment:
      POSTGRES_PASSWORD: 'perpl'
      POSTGRES_USER: 'perpl'
      PGUSER: 'perpl'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      retries: 5
    networks:
      - perpl-test-net
    # command: ["postgres", "-c", "log_statement=all"]
